[[redirects]]
  from = "/api/*"
  to = "https://api.openweathermap.org/data/3.0/onecall/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = “/*”
  to = “/index.html”
  status = 200